[versions]
kotlinpoet-ksp-version = "1.17.0"
ksp-symbol-processing-version= "2.0.0-1.0.22"
moshi-version = "1.15.1"
[libraries]
com-google-devtools-ksp-symbol-processing-api={ module="com.google.devtools.ksp:symbol-processing-api",version.ref="ksp-symbol-processing-version"}
com-google-devtools-ksp-symbol-processing-gradle-plugin = {module ="com.google.devtools.ksp:symbol-processing-gradle-plugin",version.ref="ksp-symbol-processing-version"}
com-google-devtools-ksp-symbol-processing = {module ="com.google.devtools.ksp:symbol-processing" ,version.ref="ksp-symbol-processing-version"}
com-squareup-moshi = {module ="com.squareup.moshi:moshi",version.ref="moshi-version"}
com-squareup-kotlinpoet-ksp = {module = "com.squareup:kotlinpoet-ksp",version.ref = "kotlinpoet-ksp-version"}
[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }




